### ISSUE TITLE
Notes on code reviewing

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/master-reference#650] opened 2017-09-29 17:00 UTC
The [Notes on code reviewing](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/code-reviews.md) are great as far as they go, but we could do with a more in-depth and sequential guide to how to review code. The [Questions](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/code-reviews.md#guide-ask-yourself-the-code-author-the-following-questions) sections is lengthy and in no particular order and does not give examples of good and bad practice. For such an important skill, we give too little guidance on how to do it well.

**Comment by jsms90** [comment] 2017-10-03 13:08
Kind of a duplicate of #402

**Comment by sofer** [comment] 2017-10-15 20:27
> Better guidance on code reviewing @eliascodes @ZooeyMiller

https://github.com/foundersandcoders/london-programme/issues/477

**Comment by sofer** [comment] 2017-10-20 11:26
@ZooeyMiller I spoke to @eliascodes briefly about this yesterday. 

This first thing to say is this is important, but not necessarily urgent, and can be addressed incrementally.

This [list of questions](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/code-reviews.md#guide-ask-yourself-the-code-author-the-following-questions) is only mildly helpful. It could be made much more useful if it was reviewed, put in a sensible order and annotated with examples.

With Elias in London, @finnhodgkin in Nazareth and you in Gaza, it might be a nice idea to build it up over the course of Weeks 1-4 and road test it with the students.

**Comment by eliascodes** [comment] 2017-10-24 11:38
It might be useful for the notes to build cumulatively week-to-week. Naturally there are things that you should be looking out for in week 4 that don't apply at all in week 1.

**Comment by ZooeyMiller** [comment] 2017-11-20 07:06
With reference to the notes in #731, I think something we should emphasise is the **human aspect of code reviewing**. 

We touch on this with "No sarcasm" but I think it deserves to be expanded upon. Code review is essentially an exercise in giving feedback, and it needs to be understood by the person who's code is being reviewed, that it is a tool to help them learn, and by the reviewer, that they need to be sensitive, and human about it.

**Comment by astroash** [comment] 2018-01-02 11:27
@sofer can this be closed as we now have [this doc](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/code-review.md)

**Closed** 2018-01-02 14:59 UTC
Labels: curriculum-wide, discussion, help wanted, week-toolkit
