### ISSUE TITLE
week 4 code along needs more time

### ISSUE THREAD

**Issue by ZooeyMiller** [foundersandcoders/master-reference#520] opened 2017-07-23 11:51 UTC
In both London and Nazareth the [Node-Intro-Workshop](https://github.com/foundersandcoders/node-intro-workshop) has taken longer than allocated to it. 

Both times we worked until 14:30 to complete it. (with Lunch break, so 3.5 hours working time), I would recommend we update the schedule to include this, as I would not want to cut out any of the information which is currently in there.

**Comment by paulhanna1933** [comment] 2017-09-11 12:02
I think it's hard to gauge how long a code along workshop is going to take as it seems that the biggest hold up is when students get typos. Also, typos seem to be common with code alongs and it requires a stop and go process where one mentor is leading the code along while another mentor is walking around helping fix errors. The issue is that sometimes  the entire code along needs to come to a halt  depending on the number of typos and time that it will take to debug. 

I think a good idea to solve this issue is that whenever we have code along workshops we could have a number of completion points in the workshop. Each completion point has a branch which can be checked out in order to start a clean slate for the point of the workshop that the class is currently in. Example if at mid point I run into some issues that I just can't figure out for the life of me, I can wait until the class get's to the next completion point to checkout that branch and start fresh again.

Regards, 
Sajeda & Paul

**Comment by zurda** [comment] 2019-05-10 21:41
It's been a while since this was opened. Is this still an issue that needs addressing?

**Comment by m4v15** [comment] 2019-05-13 11:39
I think this can probably be closed it is so long and some many iterations have happened since, it's hard to know if the schedule even has the same time allocated fro this as it did then

**Closed** 2019-05-13 12:11 UTC
Labels: week-node-1
